version: '3'
services:
  rust:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: postgres:11.5
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - db.env
    ports:
      - 5432:5432
volumes:
  postgres:
    driver: local
